apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: employees
        image: idrisskhaled96/gestion-employes:latest
        envFrom:
        - secretRef:
            name: employees-env
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: employees
spec:
  selector:
    app: employees
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  
